### ISSUE TITLE
Stop speaking and catch up to the current utterance

### ISSUE THREAD

**Issue by jwill** [mohamedmansour/accessible-hangouts-extension#2]
If someone pastes a really long message into the chat, it can interrupt the user from following what people are saying.

The extension should allow the person to stop all current utterances and catch up(skipping the backlog of messages).

**Comment by mohamedmansour** [comment]
testing from mobile phone.

**Comment by jwill** [comment]
Closing due to age of issue. Hangouts has likely changed significantly in the interim.
